### ISSUE TITLE
Upstream Viewer Camera Z-axis Constraint Conflicts with OpenSim Underwater Builds

### ISSUE THREAD

**Issue by humbletim** [metaverse-crossroads/hypergrid-junction#2]
A discrepancy in permissible camera altitude limits between Second Life and OpenSim environments has resulted in a user-facing bug in Firestorm viewers. While OpenSim allows builds and avatar movement at altitudes below Z=0, recent changes in the Linden Lab viewer code (likely stemming from SL-20206 and SL-20430) introduced a camera constraint limiting the minimum viewable altitude to Z=0. 

This discrepancy causes significant usability issues for Firestorm users interacting with OpenSim regions featuring negative altitude builds. Notably, avatars situated below Z=0 cannot be viewed in the customary third-person perspective, leading to a disorienting and frustrating user experience.

This issue highlights the need for a nuanced approach to address the divergent requirements of both Second Life and OpenSim environments. This investigation is ongoing and aims to promote interoperability between these interconnected ecosystems. Contributions and insights from all stakeholders are welcomed. 

see also: 
- [ \[FIRE-33613\] \[OpenSim\] \[PBR\] Camera cannot be located at negative Z](https://jira.firestormviewer.org/browse/FIRE-33613)

**Comment by humbletim** [comment]
This issue arises from the interplay of several factors:

- **OpenSim's allowance for negative altitude builds:** This feature is not present in Second Life, leading to a fundamental difference in permissible world geometry.
- **Linden Lab's implementation of a camera constraint at Z=0:** This change, likely intended for Second Life environments, unintentionally impacts Firestorm viewers used in OpenSim contexts.
- **Firestorm's inheritance of Linden Lab viewer code:** While Firestorm actively supports OpenSim, its reliance on upstream code introduces vulnerabilities to SL-specific changes that may not be compatible with OpenSim.

Further investigation has pinpointed the specific code sections responsible for this constraint (details to be added as a separate comment). This issue necessitates a careful consideration of the needs of both OpenSim and Second Life users, aiming for a solution that reconciles these distinct requirements and restores the expected functionality of the Firestorm viewer in OpenSim environments.

**Comment by humbletim** [comment]
The viewer calculations resulting in reduced camera range:
- SLOS Viewer (upstream): [indra/newview/llagentcamera.cpp#L2004-L2012](https://github.com/secondlife/viewer/blob/e1623bb276f83a43ce7a197e388720c05bdefe61/indra/newview/llagentcamera.cpp#L2004-L2012)
- Firestorm TPV (downstream): [indra/newview/llagentcamera.cpp#L2147-L2155 ](https://github.com/metaverse-crossroads/phoenix-firestorm/blob/eeae13c7a4be9442e812254b6eba7a602e06eee4/indra/newview/llagentcamera.cpp#L2147-L2155  )

Note that the `DisableCameraConstraints` viewer setting intuitively should already be capable of disarming this newly introduced camera constraint -- however, this oversight (if an oversight) could be considered a TPV-wide regression and potentially best solved upstream (perhaps by incorporating a corresponding [!isDisableCameraConstraints()](https://github.com/secondlife/viewer/blob/e1623bb276f83a43ce7a197e388720c05bdefe61/indra/newview/llagentcamera.cpp#L103-L107) check around the new minZ restrictions above).

**Comment by humbletim** [comment]
Regarding discussion of a `-100` [OpenSim lower altitude limits](https://github.com/opensim/opensim/blob/cbe6071f292a7a7a5f490931b951c86d87b002ab/OpenSim/Framework/Constants.cs#L55-L57) -- which seems relevant towards calculating a similar glass floor constraint as LL does (taking into account this OpenSim-specific lower overall limit): it appears these constants are advertised through `OpenSimExtras` as part of Simulation Features, but not yet consumed anywhere on the viewer side:

`MinSimHeight` / `MinTerrainHeightMap` references:
- [opensim/opensim -- code search](https://github.com/search?q=repo%3Aopensim%2Fopensim+%28MinSimHeight+OR+MinHeightMap%29&type=code)
- [FirestormViewer/phoenix-firestorm -- code search](https://github.com/search?q=repo%3AFirestormViewer%2Fphoenix-firestorm+%28MinSimHeight+OR+MinHeightMap%29&type=code) (presently no results)

Instrumenting support for consuming these constants would require figuring out which one is meant to apply in this camera constraint case -- given that the glass floor constraint takes into account the terrain height beneath the camera, though with constraints disabled by settings might instead premise on overall simulation floor. In Firestorm the main entry point for consuming advertised simulation features is in [indra/newview/lfsimfeaturehandler.cpp](https://github.com/FirestormViewer/phoenix-firestorm/blob/c940fca2f4229fbaf99f274e3cff959bfb2b0df6/indra/newview/lfsimfeaturehandler.cpp#L91-L93).

**Comment by aiaustin** [comment]
Note that the avatar can go down below Z = 0m and can still be seen in the camera view, but the position of the camera is locked to be at Z=0m or above in recent Firestorm 7.* Beta versions.  The camera could go down to negative Z in the current Firestorm release 6.6.17. So the new limit is a regression  for OpenSim users.

OpenSim current server code has -100m to +50000m build range.

        public const float MinSimulationHeight = -100f;
        public const float MaxSimulationHeight = 50000f;
        public const float MinTerrainHeightmap = -100f;
        public const float MaxTerrainHeightmap = 4000f;
        public const float MinWaterHeight = 0;
        public const float MaxWaterHeight = 8000f;

**Comment by aiaustin** [comment]
Note avatar can be seen even when its below Z = 0m in OpenSim. But the camera cannot follow the avatar and is clamped to a minimum of Z=0m in recent Firestorm 7.* Beta versions.

**Comment by humbletim** [comment]
@aiaustin additional notes (migrated from staging PR metaverse-crossroads/phoenix-firestorm#2):
> Just to document some things about OpenSimulator Min and Max heights...
> 
> MisterblueGuy — Discord on 18-May-2024:
> In OpenSim.Framework.Constants there is "MinSimulationHeight" which is set to -100f. Unless there is some special mechanism to change the constants somewhere, this value cannot be changed without compiling the sources.
> 
> Constants.MaxSimulationHeight = 50000f;
> although, Constants.RegionHeight = 4096;
> for physics, ubOde uses Constants.MinSimulationHeight. BulletSim creates a solid physical plane at -500m so that objects don't fall to infinity if they somehow get under the terrain. ubOde must do similar.
